kind: PersistentVolume
apiVersion: v1
metadata:
  name: notes-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/notes-app

